// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bitcoinwalletcontracts.proto

/*
Package bitcoinwalletcontracts is a generated protocol buffer package.

It is generated from these files:
	bitcoinwalletcontracts.proto

It has these top-level messages:
	BitcoinWalletCreated
*/
package bitcoinwalletcontracts

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BitcoinWalletCreated struct {
	Address     string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	NameOfOwner string `protobuf:"bytes,2,opt,name=nameOfOwner" json:"nameOfOwner,omitempty"`
}

func (m *BitcoinWalletCreated) Reset()                    { *m = BitcoinWalletCreated{} }
func (m *BitcoinWalletCreated) String() string            { return proto.CompactTextString(m) }
func (*BitcoinWalletCreated) ProtoMessage()               {}
func (*BitcoinWalletCreated) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BitcoinWalletCreated) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *BitcoinWalletCreated) GetNameOfOwner() string {
	if m != nil {
		return m.NameOfOwner
	}
	return ""
}

func init() {
	proto.RegisterType((*BitcoinWalletCreated)(nil), "bitcoinwalletcontracts.BitcoinWalletCreated")
}

func init() { proto.RegisterFile("bitcoinwalletcontracts.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 121 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x49, 0xca, 0x2c, 0x49,
	0xce, 0xcf, 0xcc, 0x2b, 0x4f, 0xcc, 0xc9, 0x49, 0x2d, 0x49, 0xce, 0xcf, 0x2b, 0x29, 0x4a, 0x4c,
	0x2e, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0xc3, 0x2e, 0xab, 0x14, 0xc4, 0x25,
	0xe2, 0x04, 0x91, 0x09, 0x07, 0xcb, 0x38, 0x17, 0xa5, 0x26, 0x96, 0xa4, 0xa6, 0x08, 0x49, 0x70,
	0xb1, 0x27, 0xa6, 0xa4, 0x14, 0xa5, 0x16, 0x17, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0xc1,
	0xb8, 0x42, 0x0a, 0x5c, 0xdc, 0x79, 0x89, 0xb9, 0xa9, 0xfe, 0x69, 0xfe, 0xe5, 0x79, 0xa9, 0x45,
	0x12, 0x4c, 0x60, 0x59, 0x64, 0xa1, 0x24, 0x36, 0xb0, 0x95, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xa9, 0xd3, 0xf9, 0xba, 0x92, 0x00, 0x00, 0x00,
}
