// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bitcoinwalletcontracts.proto

/*
Package bitcoinwalletcontracts is a generated protocol buffer package.

It is generated from these files:
	bitcoinwalletcontracts.proto

It has these top-level messages:
	BitcoinWalletCreated
	DepositMade
	PaymentMade
	Amount
*/
package bitcoinwalletcontracts

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BitcoinWalletCreated struct {
	Address     string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	NameOfOwner string `protobuf:"bytes,2,opt,name=nameOfOwner" json:"nameOfOwner,omitempty"`
}

func (m *BitcoinWalletCreated) Reset()                    { *m = BitcoinWalletCreated{} }
func (m *BitcoinWalletCreated) String() string            { return proto.CompactTextString(m) }
func (*BitcoinWalletCreated) ProtoMessage()               {}
func (*BitcoinWalletCreated) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BitcoinWalletCreated) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *BitcoinWalletCreated) GetNameOfOwner() string {
	if m != nil {
		return m.NameOfOwner
	}
	return ""
}

type DepositMade struct {
	Amount *Amount `protobuf:"bytes,1,opt,name=amount" json:"amount,omitempty"`
}

func (m *DepositMade) Reset()                    { *m = DepositMade{} }
func (m *DepositMade) String() string            { return proto.CompactTextString(m) }
func (*DepositMade) ProtoMessage()               {}
func (*DepositMade) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DepositMade) GetAmount() *Amount {
	if m != nil {
		return m.Amount
	}
	return nil
}

type PaymentMade struct {
	DestinationAddress string  `protobuf:"bytes,1,opt,name=destinationAddress" json:"destinationAddress,omitempty"`
	Amount             *Amount `protobuf:"bytes,2,opt,name=amount" json:"amount,omitempty"`
}

func (m *PaymentMade) Reset()                    { *m = PaymentMade{} }
func (m *PaymentMade) String() string            { return proto.CompactTextString(m) }
func (*PaymentMade) ProtoMessage()               {}
func (*PaymentMade) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PaymentMade) GetDestinationAddress() string {
	if m != nil {
		return m.DestinationAddress
	}
	return ""
}

func (m *PaymentMade) GetAmount() *Amount {
	if m != nil {
		return m.Amount
	}
	return nil
}

type Amount struct {
	Amount   float32 `protobuf:"fixed32,1,opt,name=amount" json:"amount,omitempty"`
	Currency string  `protobuf:"bytes,2,opt,name=currency" json:"currency,omitempty"`
}

func (m *Amount) Reset()                    { *m = Amount{} }
func (m *Amount) String() string            { return proto.CompactTextString(m) }
func (*Amount) ProtoMessage()               {}
func (*Amount) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Amount) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Amount) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func init() {
	proto.RegisterType((*BitcoinWalletCreated)(nil), "bitcoinwalletcontracts.BitcoinWalletCreated")
	proto.RegisterType((*DepositMade)(nil), "bitcoinwalletcontracts.DepositMade")
	proto.RegisterType((*PaymentMade)(nil), "bitcoinwalletcontracts.PaymentMade")
	proto.RegisterType((*Amount)(nil), "bitcoinwalletcontracts.Amount")
}

func init() { proto.RegisterFile("bitcoinwalletcontracts.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0x3f, 0x4b, 0xc4, 0x40,
	0x10, 0xc5, 0xb9, 0x14, 0x51, 0x67, 0xbb, 0x45, 0x8e, 0x20, 0x22, 0x47, 0x2a, 0xab, 0x14, 0x0a,
	0x56, 0x36, 0xe7, 0x9f, 0x52, 0x4e, 0xd2, 0x58, 0xcf, 0xed, 0x8e, 0xb0, 0x70, 0x99, 0x3d, 0x76,
	0x27, 0x84, 0x7c, 0x7b, 0x61, 0x93, 0x48, 0x02, 0xb1, 0xb0, 0x9c, 0xf7, 0x7b, 0xbc, 0xf7, 0x76,
	0xe1, 0xf6, 0xe8, 0xc4, 0x78, 0xc7, 0x1d, 0x9e, 0x4e, 0x24, 0xc6, 0xb3, 0x04, 0x34, 0x12, 0xab,
	0x73, 0xf0, 0xe2, 0xf5, 0x76, 0x9d, 0x96, 0x35, 0x5c, 0xbf, 0x0c, 0xe4, 0x2b, 0x91, 0xd7, 0x40,
	0x28, 0x64, 0x75, 0x01, 0x17, 0x68, 0x6d, 0xa0, 0x18, 0x8b, 0xcd, 0x6e, 0x73, 0x7f, 0x55, 0x4f,
	0xa7, 0xde, 0x81, 0x62, 0x6c, 0xe8, 0xf0, 0x7d, 0xe8, 0x98, 0x42, 0x91, 0x25, 0x3a, 0x97, 0xca,
	0x77, 0x50, 0x6f, 0x74, 0xf6, 0xd1, 0xc9, 0x07, 0x5a, 0xd2, 0x4f, 0x90, 0x63, 0xe3, 0x5b, 0x96,
	0x94, 0xa4, 0x1e, 0xee, 0xaa, 0x3f, 0x96, 0xee, 0x93, 0xab, 0x1e, 0xdd, 0x65, 0x0b, 0xea, 0x13,
	0xfb, 0x86, 0x78, 0x88, 0xa9, 0x40, 0x5b, 0x8a, 0xe2, 0x18, 0xc5, 0x79, 0xde, 0x2f, 0xc6, 0xad,
	0x90, 0x59, 0x6d, 0xf6, 0xaf, 0xda, 0x67, 0xc8, 0x07, 0x45, 0x6f, 0x17, 0xc3, 0xb3, 0xc9, 0xa1,
	0x6f, 0xe0, 0xd2, 0xb4, 0x21, 0x10, 0x9b, 0x7e, 0x7c, 0xfe, 0xef, 0x7d, 0xcc, 0xd3, 0x77, 0x3f,
	0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0xc3, 0x44, 0x56, 0xba, 0x8e, 0x01, 0x00, 0x00,
}
