// Code generated by protoc-gen-go. DO NOT EDIT.
// source: eventsourcingmsg.proto

/*
Package eventsourcingcontracts is a generated protocol buffer package.

It is generated from these files:
	eventsourcingmsg.proto

It has these top-level messages:
	EventEnvelope
	TestMessage
*/
package eventsourcingcontracts

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EventEnvelope struct {
	TypeName    string `protobuf:"bytes,1,opt,name=type_name,json=typeName" json:"type_name,omitempty"`
	MessageData []byte `protobuf:"bytes,2,opt,name=message_data,json=messageData,proto3" json:"message_data,omitempty"`
}

func (m *EventEnvelope) Reset()                    { *m = EventEnvelope{} }
func (m *EventEnvelope) String() string            { return proto.CompactTextString(m) }
func (*EventEnvelope) ProtoMessage()               {}
func (*EventEnvelope) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *EventEnvelope) GetTypeName() string {
	if m != nil {
		return m.TypeName
	}
	return ""
}

func (m *EventEnvelope) GetMessageData() []byte {
	if m != nil {
		return m.MessageData
	}
	return nil
}

type TestMessage struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	I  int32  `protobuf:"varint,2,opt,name=i" json:"i,omitempty"`
}

func (m *TestMessage) Reset()                    { *m = TestMessage{} }
func (m *TestMessage) String() string            { return proto.CompactTextString(m) }
func (*TestMessage) ProtoMessage()               {}
func (*TestMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TestMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TestMessage) GetI() int32 {
	if m != nil {
		return m.I
	}
	return 0
}

func init() {
	proto.RegisterType((*EventEnvelope)(nil), "eventsourcingcontracts.EventEnvelope")
	proto.RegisterType((*TestMessage)(nil), "eventsourcingcontracts.TestMessage")
}

func init() { proto.RegisterFile("eventsourcingmsg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 170 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0xce, 0x41, 0xeb, 0x82, 0x40,
	0x10, 0x05, 0x70, 0x56, 0xf8, 0xff, 0xc9, 0xd1, 0x3a, 0xec, 0x21, 0x84, 0x2e, 0xe6, 0x49, 0x08,
	0xba, 0xf4, 0x15, 0xf2, 0x58, 0x81, 0x74, 0x97, 0x49, 0x07, 0x59, 0x68, 0x77, 0x65, 0x67, 0x12,
	0xfa, 0xf6, 0xa1, 0x79, 0xe9, 0xfa, 0x7b, 0xbc, 0xc7, 0x83, 0x2d, 0x8d, 0xe4, 0x84, 0xfd, 0x2b,
	0xb4, 0xc6, 0xf5, 0x96, 0xfb, 0xe3, 0x10, 0xbc, 0x78, 0xfd, 0xeb, 0xad, 0x77, 0x12, 0xb0, 0x15,
	0x2e, 0x6e, 0xb0, 0xae, 0xa6, 0xa4, 0x72, 0x23, 0x3d, 0xfd, 0x40, 0x7a, 0x07, 0xb1, 0xbc, 0x07,
	0x6a, 0x1c, 0x5a, 0xca, 0x54, 0xae, 0xca, 0xb8, 0x5e, 0x4d, 0x70, 0x45, 0x4b, 0x7a, 0x0f, 0xa9,
	0x25, 0x66, 0xec, 0xa9, 0xe9, 0x50, 0x30, 0x8b, 0x72, 0x55, 0xa6, 0x75, 0xb2, 0xd8, 0x19, 0x05,
	0x8b, 0x03, 0x24, 0x77, 0x62, 0xb9, 0x7c, 0x49, 0x6f, 0x20, 0x32, 0xdd, 0xb2, 0x13, 0x99, 0x4e,
	0xa7, 0xa0, 0xcc, 0x5c, 0xfb, 0xab, 0x95, 0x79, 0xfc, 0xcf, 0xe7, 0x4e, 0x9f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x09, 0xbb, 0xc6, 0x48, 0xb6, 0x00, 0x00, 0x00,
}
